[global]
theme = 'radium' # currently only offline themes are allowed
providers = ['node', 'perl', 'python3', 'ruby'] # blacklists these providers

# Sign {{{
[sign]
signcolumn = 'yes'

[sign.diagnostic.error]
name = 'DiagnosticSignError'
text = ''
texthl = 'DiagnosticsSignErrorText'
linehl = 'DiagnosticsSignErrorLine'
numhl = 'DiagnosticsSignErrorNum'

[sign.diagnostic.hint]
name = 'DiagnosticSignHint'
text = ' '
texthl = 'DiagnosticsSignHintText'
linehl = 'DiagnosticsSignHintLine'
numhl = 'DiagnosticsSignHintNum'

[sign.diagnostic.info]
name = 'DiagnosticSignInfo'
text = ''
texthl = 'DiagnosticsSignInfoText'
linehl = 'DiagnosticsSignInfoLine'
numhl = 'DiagnosticsSignInfoNum'

[sign.diagnostic.warn]
name = 'DiagnosticSignWarn'
text = ''
texthl = 'DiagnosticsSignWarnText'
linehl = 'DiagnosticsSignWarnLine'
numhl = 'DiagnosticsSignWarnNum'

[sign.lightbulb]
name = 'LightBulbSign'
text = ''
texthl = 'LspDiagnosticsSignHint'
numhl = 'LspDiagnosticsSignHint'
# }}}

[editor]
line_number = 'absolute' # relative | absolute | none
scrolloff = 8
sidescrolloff = 8
shell = '$SHELL'

[editor.cursor]
cursorline = false
cursorbind = false
cursorcolumn = false

[editor.cursor.options]
line = true # highlight the text line of the cursor
screenline = false # highlight only the screen line of the cursor
number = false # highlight the line number of the cursor
both = false # alias for the values line and number
# NOTE: "line" and "screenline" cannot be used together.

[editor.mouse]
enabled = true # enable/disable mouse support
# enable mouse support only for:
normal = true # normal mode
insert = false # insert mode
visual = true # visual mode
cmdline = false # command-line mode
help = false # all previous modes when editing a help file
previous = false # all previous modes
prompt = false # for hit-enter and more-prompt prompt

# Keymap {{{
[keymap]
# applies for all of the following keymaps
remap = false
silent = true

[keymap.normal]
'<leader>q' = ':copen<CR>'
'<C-[>' = '<CMD>nohl<CR>'
'<leader>Y' = '"+Y'
'<leader>#' = ':g/<C-R><C-W>/#<CR>'
'<C-H>' = '<C-W>h'
'<C-J>' = '<C-W>j'
'<C-K>' = '<C-W>k'
'<C-L>' = '<C-W>l'
'<C-Up>' = ':resize -2<CR>'
'<C-Down>' = ':resize +2<CR>'
'<C-Left>' = ':vertical resize -2<CR>'
'<C-Right>' = ':vertical resize +2<CR>'
'[q' = ':cprevious<CR>'
']q' = ':cnext<CR>'
'[Q' = ':cfirst<CR>'
']Q' = ':clast<CR>'
'[l' = ':lprevious<CR>'
']l' = ':lnext<CR>'
'[b' = ':bprevious<CR>'
']b' = ':bnext<CR>'
'[a' = ':previous<CR>'
']a' = ':next<CR>'
'<leader><leader>' = ':Track<CR>'
'<leader>aa' = ':TrackMark<CR>'
'<leader>dd' = ':TrackUnmark<CR>'
'<leader>c' = ':lua require"dharmx.utils".close()<CR>'
'<leader>u' = ':UndotreeToggle<CR>'
'<F1>' = ':ColorizerToggle<CR>'
'<F2>' = ':setlocal spell!<CR>'
'<F3>' = ':make<CR>'
'<C-S>' = ':update<CR>'
'<C-N>' = ':RnvimrToggle<CR>'
'<C-\>' = ':ToggleTerm<CR>'
'<leader>bb' = ':Telescope buffers<CR>'
'<leader>ff' = ':Telescope media<CR>'
'<leader>gg' = ':Telescope live_grep<CR>'
'<leader>mm' = ':Telescope marks<CR>'
'<leader>rr' = ':Telescope registers<CR>'
'<leader>jj' = ':Telescope jumplist<CR>'
'<leader>ll' = ':Telescope loclist<CR>'
'<A-k>' = ':MoveLine(-1)<CR>'
'<A-j>' = ':MoveLine(1)<CR>'
'<A-l>' = ':MoveHChar(1)<CR>'
'<A-h>' = ':MoveHChar(-1)<CR>'
'<leader>wf' = ':MoveWord(1)<CR>'
'<leader>wb' = ':MoveWord(-1)<CR>'
'<leader>s' = 'mm$F r<CR>`m'
'<up>' = '<nop>'
'<down>' = '<nop>'
'<left>' = '<nop>'
'<right>' = '<nop>'

[keymap.visual]
'<A-j>' = ':MoveBlock(1)<CR>'
'<A-k>' = ':MoveBlock(-1)<CR>'
'<A-h>' = ':MoveHBlock(-1)<CR>'
'<A-l>' = ':MoveHBlock(1)<CR>'
'<' = '<gv'
'>' = '>gv'
'<leader>y' = '"+y'
'<up>' = '<nop>'
'<down>' = '<nop>'
'<left>' = '<nop>'
'<right>' = '<nop>'

[keymap.insert]
'<up>' = '<nop>'
'<down>' = '<nop>'
'<left>' = '<nop>'
'<right>' = '<nop>'
# }}}

# Variables {{{
[variables]
python3_host_prog = 'python3'
neovide_refresh_rate = 60
neovide_transparency = 1.0
neovide_no_idle = 1
neovide_profiler = 0
neovide_touch_deadzone = 6.0
neovide_input_use_logo = 1
neovide_remember_window_size = 1
neovide_touch_drag_timeout = 0.17
neovide_cursor_animation_length = 0.13
neovide_cursor_trail_length = 0.8
neovide_cursor_antialiasing = 1
neovide_cursor_unfocused_outline_width = 0.125
neovide_cursor_vfx_mode = 'railgun'
neovide_cursor_vfx_opacity = 200.0
neovide_cursor_vfx_particle_lifetime = 1.2
neovide_cursor_vfx_particle_density = 7.0
neovide_cursor_vfx_particle_speed = 10.0
neovide_cursor_vfx_particle_phase = 1.5
neovide_cursor_vfx_particle_curl = 1.0
neovide_padding_top = 10
neovide_padding_left = 10
neovide_padding_right = 10
neovide_padding_bottom = 10
# }}}

# Options {{{
[options]
backupdir = '${NVIM_STATE}/backup'
spellfile = '${NVIM_CONFIG}/spell/words.add'
guifont = 'Iosevka Nerd Font,Cooper Hewitt:h13'
linespace = 8
swapfile = false
backup = true
spell = false
wildmode = ['longest', 'list', 'full']
spelllang = ['en_us', 'en_gb', 'cjk']
spellsuggest = ['best', 9]
spelloptions = ['camel', 'noplainbuffer']
exrc = false
termguicolors = true
textwidth = 120
colorcolumn = '120'
laststatus = 3
backspace = ['indent', 'eol', 'start']
completeopt = ['menuone', 'noselect']
title = true
hidden = true
splitbelow = true
splitright = true
clipboard = ""
cmdheight = 1
autowrite = true
autoindent = true
expandtab = true
shiftwidth = 2
smartindent = true
wildignore = ['*/cache/*', '*/tmp/*']
foldcolumn = 'auto'
foldmethod = 'marker'
ignorecase = false
smartcase = true
undolevels = 10000
numberwidth = 1
tabstop = 4
timeoutlen = 250
undofile = true
updatetime = 500
wrap = false
showmode = true
showcmd = true
showtabline = 1
hlsearch = true
conceallevel = 2
pumheight = 25
pumwidth = 35
pumblend = 0
winblend = 0
history = 10000
emoji = true
ruler = true
list = true
menuitems = 30
magic = true
icon = true
# }}}
