[[spec]]
plugin = "kylechui/nvim-surround"
config = true
event = [ "CmdlineEnter", "InsertEnter", "CursorHold", "CursorMoved" ]

[[spec]]
plugin = "monaqa/dial.nvim"
keys = "" # "factory" is a reserved value the function will be picked up from factory.lua
config = "" # "factory" is a reserved value the function will be picked up from factory.lua
enabled = "" # "factory" is a reserved value the function will be picked up from factory.lua
cond = "" # "factory" is a reserved value the function will be picked up from factory.lua
init = "" # "factory" is a reserved value the function will be picked up from factory.lua
build = "" # "factory" is a reserved value the function will be picked up from factory.lua
event = "" # "factory" is a reserved value the function will be picked up from factory.lua
ft = "" # "factory" is a reserved value the function will be picked up from factory.lua

[[spec]]
plugin = "max397574/better-escape.nvim"
opts = ""
event = [ "CmdlineEnter", "InsertEnter", "CursorHold", "CursorMoved" ]

[[spec]]
plugin = "johmsalas/text-case.nvim"

[[spec]]
plugin = "tversteeg/registers.nvim"
config = ""
cmd = "Registers"
keys = ""

[[spec]]
plugin = "NvChad/nvim-colorizer.lua"
config = true
cmd = "ColorizerToggle"

[[spec]]
plugin = "AndrewRadev/linediff.vim"
cmd = "Linediff"

[[spec]]
plugin = "itchyny/vim-highlighturl"
event = "CursorMoved"

[[spec]]
plugin = "tyru/open-browser.vim"
event = "CmdlineEnter"

[[spec]]
plugin = "aurum77/live-server.nvim"
opts = ""
build = ""
cmd = [ "LiveServer", "LiveServerStart", "LiveServerStop" ]

[[spec]]
plugin = "kevinhwang91/rnvimr"
init = ""

[[spec]]
plugin = "sindrets/diffview.nvim"
config = true
event = "CmdlineEnter"

[[spec]]
plugin = "akinsho/toggleterm.nvim"
config = ""
cmd = "ToggleTerm"

[[spec]]
plugin = "kevinhwang91/nvim-hlslens"
config = true
event = "CmdlineEnter"
keys = ""

[[spec]]
plugin = "kovetskiy/sxhkd-vim"
ft = "sxhkd"

[[spec]]
plugin = "TimUntersberger/neogit"
opts = ""
cmd = "Neogit"

[[spec]]
plugin = "lewis6991/gitsigns.nvim"
config = ""
event = [ "CmdlineEnter", "InsertEnter", "CursorHold", "CursorMoved" ]

[[spec]]
plugin = "numToStr/Comment.nvim"
config = ""
keys = ""

[[spec]]
plugin = "phelipetls/vim-hugo"
ft = "markdown"

[[spec]]
plugin = "robertbasic/vim-hugo-helper"
ft = "markdown"

[[spec]]
plugin = "fedepujol/move.nvim"
event = [ "CursorHold", "CursorMoved", "InsertEnter", "CmdlineEnter" ]

[[spec]]
plugin = "tpope/vim-repeat"
event = [ "CursorHold", "CursorMoved", "InsertEnter", "CmdlineEnter" ]

[[spec]]
plugin = "mbbill/undotree"
init = ""
cmd = "UndotreeToggle"

[[spec]]
plugin = "toppair/peek.nvim"
opts = ""
build = ""
ft = "markdown"

[[spec]]
plugin = "rafamadriz/friendly-snippets"

[[spec]]
plugin = "L3MON4D3/LuaSnip"
config = ""
event = "InsertEnter"

[[spec]]
plugin = "gelguy/wilder.nvim"
config = ""
event = "CmdlineEnter"

[[spec]]
plugin = "windwp/nvim-autopairs"
config = ""
event = "InsertEnter"

[[spec]]
plugin = "hrsh7th/nvim-cmp"
dependencies = [ "saadparwaiz1/cmp_luasnip", "hrsh7th/cmp-nvim-lsp-signature-help", "hrsh7th/cmp-buffer", "hrsh7th/cmp-nvim-lsp" ]
config = ""
event = "InsertEnter"
keys = ""

[[spec]]
plugin = "saadparwaiz1/cmp_luasnip"

[[spec]]
plugin = "hrsh7th/cmp-nvim-lsp-signature-help"

[[spec]]
plugin = "hrsh7th/cmp-buffer"

[[spec]]
plugin = "hrsh7th/cmp-nvim-lsp"

[[spec]]
plugin = "tami5/sqlite.lua"

[[spec]]
plugin = "nvim-lua/plenary.nvim"

[[spec]]
plugin = "MunifTanjim/nui.nvim"

[[spec]]
plugin = "vijaymarupudi/nvim-fzf"

[[spec]]
plugin = "williamboman/mason.nvim"
config = ""

[[spec]]
plugin = "folke/neoconf.nvim"

[[spec]]
plugin = "folke/neodev.nvim"

[[spec]]
plugin = "b0o/schemastore.nvim"

[[spec]]
plugin = "kosayoda/nvim-lightbulb"
config = ""

[[spec]]
plugin = "SmiteshP/nvim-navic"
config = ""

[[spec]]
plugin = "simrat39/rust-tools.nvim"

[[spec]]
plugin = "mfussenegger/nvim-jdtls"

[[spec]]
plugin = "williamboman/mason-lspconfig.nvim"
dependencies = [ "williamboman/mason.nvim" ]
opts = ""

[[spec]]
plugin = "neovim/nvim-lspconfig"
config = ""
cmd = "LspStart"

[[spec]]
plugin = "j-hui/fidget.nvim"
config = ""
tag = "legacy"
event = "LspAttach"

[[spec]]
plugin = "mhartington/formatter.nvim"
config = ""
event = "LspAttach"

[[spec]]
plugin = "jayp0521/mason-null-ls.nvim"
opts = ""

[[spec]]
plugin = "jose-elias-alvarez/null-ls.nvim"
dependencies = [ "WhoIsSethDaniel/mason-tool-installer.nvim", "jayp0521/mason-null-ls.nvim" ]
config = ""
event = "LspAttach"

[[spec]]
plugin = "WhoIsSethDaniel/mason-tool-installer.nvim"
opts = ""

[[spec]]
plugin = "mfussenegger/nvim-dap"
dependencies = [ "jayp0521/mason-nvim-dap.nvim" ]

[[spec]]
plugin = "jayp0521/mason-nvim-dap.nvim"
config = ""

[[spec]]
plugin = "rcarriga/nvim-dap-ui"
config = ""
event = "LspAttach"

[[spec]]
plugin = "nvim-telescope/telescope.nvim"
dependencies = [ "nvim-telescope/telescope-symbols.nvim" ]
config = ""
cmd = "Telescope"

[[spec]]
plugin = "dharmx/track.nvim"
dev = true
config = true
cmd = [ "Track", "TrackPick", "TrackMark", "TrackBundleAlternate", "TrackUnmark", "TrackStashBundle", "TrackRestoreBundle" ]

[[spec]]
plugin = "nvim-telescope/telescope-ui-select.nvim"

[[spec]]
plugin = "dharmx/telescope-media.nvim"
dev = true

[[spec]]
plugin = "nvim-telescope/telescope-symbols.nvim"

[[spec]]
plugin = "nvim-telescope/telescope-dap.nvim"

[[spec]]
plugin = "nvim-treesitter/nvim-treesitter"
config = ""
build = ""
event = "BufWinEnter"

[[spec]]
plugin = "romgrk/nvim-treesitter-context"
config = ""
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]

[[spec]]
plugin = "andymass/vim-matchup"
config = ""
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]

[[spec]]
plugin = "mrjones2014/nvim-ts-rainbow"
config = ""
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]

[[spec]]
plugin = "RRethy/nvim-treesitter-textsubjects"
config = ""
keys = ""

[[spec]]
plugin = "nvim-treesitter/nvim-treesitter-textobjects"
config = ""
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]

[[spec]]
plugin = "theHamsta/nvim-dap-virtual-text"
dependencies = [ "nvim-treesitter/nvim-treesitter" ]
config = ""
event = "LspAttach"

[[spec]]
plugin = "nvim-tree/nvim-web-devicons"

[[spec]]
plugin = "petertriho/nvim-scrollbar"
config = ""
event = [ "InsertEnter", "CursorMoved" ]

[[spec]]
plugin = "rcarriga/nvim-notify"
config = ""
event = [ "CursorMoved", "CursorHold", "InsertEnter", "CmdlineEnter" ]

[[spec]]
plugin = "folke/todo-comments.nvim"
config = ""
event = [ "CursorMoved", "CursorHold", "InsertEnter", "CmdlineEnter" ]

[[spec]]
plugin = "doums/monark.nvim"
opts = ""
event = "InsertEnter"

[[spec]]
plugin = "lukas-reineke/indent-blankline.nvim"
config = ""
event = [ "CursorMoved", "CursorHold", "InsertEnter" ]

[[spec]]
plugin = "RRethy/vim-illuminate"
config = ""
event = [ "InsertEnter", "CursorMoved" ]
