[[spec]]
plugin = "kylechui/nvim-surround"
config = true
event = [ "CmdlineEnter", "InsertEnter", "CursorHold", "CursorMoved" ]

[[spec]]
plugin = "monaqa/dial.nvim"
config = "dharmx.configs.code.dial"
keys = "factory"

[[spec]]
plugin = "max397574/better-escape.nvim"
opts = "factory"
event = [ "CmdlineEnter", "InsertEnter", "CursorHold", "CursorMoved" ]

[[spec]]
plugin = "johmsalas/text-case.nvim"

[[spec]]
plugin = "tversteeg/registers.nvim"
config = "dharmx.configs.code.registers"
cmd = "Registers"
keys = "factory"

[[spec]]
plugin = "NvChad/nvim-colorizer.lua"
config = true
cmd = "ColorizerToggle"

[[spec]]
plugin = "AndrewRadev/linediff.vim"
cmd = "Linediff"

[[spec]]
plugin = "itchyny/vim-highlighturl"
event = "CursorMoved"

[[spec]]
plugin = "tyru/open-browser.vim"
event = "CmdlineEnter"

[[spec]]
plugin = "aurum77/live-server.nvim"
cmd = [ "LiveServer", "LiveServerStart", "LiveServerStop" ]
opts = "factory"
build = "factory"

[[spec]]
plugin = "kevinhwang91/rnvimr"
init = "dharmx.configs.code.ranger"
lazy = false

[[spec]]
plugin = "sindrets/diffview.nvim"
config = true
event = "CmdlineEnter"

[[spec]]
plugin = "akinsho/toggleterm.nvim"
cmd = "ToggleTerm"
config = "dharmx.configs.code.toggleterm"

[[spec]]
plugin = "kevinhwang91/nvim-hlslens"
config = true
event = "CmdlineEnter"
keys = [ "n", "N" ]

[[spec]]
plugin = "kovetskiy/sxhkd-vim"
ft = "sxhkd"

[[spec]]
plugin = "TimUntersberger/neogit"
cmd = "Neogit"
opts = "factory"

[[spec]]
plugin = "lewis6991/gitsigns.nvim"
event = [ "CmdlineEnter", "InsertEnter", "CursorHold", "CursorMoved" ]
config = "dharmx.configs.code.gitsigns"

[[spec]]
plugin = "numToStr/Comment.nvim"
keys = "factory"
config = "dharmx.configs.code.comments"

[[spec]]
plugin = "phelipetls/vim-hugo"
ft = "markdown"

[[spec]]
plugin = "robertbasic/vim-hugo-helper"
ft = "markdown"

[[spec]]
plugin = "fedepujol/move.nvim"
event = [ "CursorHold", "CursorMoved", "InsertEnter", "CmdlineEnter" ]

[[spec]]
plugin = "tpope/vim-repeat"
event = [ "CursorHold", "CursorMoved", "InsertEnter", "CmdlineEnter" ]

[[spec]]
plugin = "mbbill/undotree"
cmd = "UndotreeToggle"
init = "factory"

[[spec]]
plugin = "toppair/peek.nvim"
ft = "markdown"
opts = "factory"
build = "deno task --quiet build:fast"

[[spec]]
plugin = "rafamadriz/friendly-snippets"

[[spec]]
plugin = "L3MON4D3/LuaSnip"
event = "InsertEnter"
config = "dharmx.configs.completions.luasnip"

[[spec]]
plugin = "gelguy/wilder.nvim"
event = "CmdlineEnter"
config = "dharmx.configs.completions.wilder"

[[spec]]
plugin = "windwp/nvim-autopairs"
event = "InsertEnter"
config = "dharmx.configs.completions.autopairs"

[[spec]]
plugin = "hrsh7th/nvim-cmp"
dependencies = [ "saadparwaiz1/cmp_luasnip", "hrsh7th/cmp-nvim-lsp-signature-help", "hrsh7th/cmp-buffer", "hrsh7th/cmp-nvim-lsp" ]
event = "InsertEnter"
keys = "factory"
config = "dharmx.configs.completions"

[[spec]]
plugin = "saadparwaiz1/cmp_luasnip"

[[spec]]
plugin = "hrsh7th/cmp-nvim-lsp-signature-help"

[[spec]]
plugin = "hrsh7th/cmp-buffer"

[[spec]]
plugin = "hrsh7th/cmp-nvim-lsp"

[[spec]]
plugin = "tami5/sqlite.lua"

[[spec]]
plugin = "nvim-lua/plenary.nvim"

[[spec]]
plugin = "MunifTanjim/nui.nvim"

[[spec]]
plugin = "vijaymarupudi/nvim-fzf"

[[spec]]
plugin = "williamboman/mason.nvim"
config = "dharmx.configs.lsp.mason"

[[spec]]
plugin = "folke/neoconf.nvim"

[[spec]]
plugin = "folke/neodev.nvim"

[[spec]]
plugin = "b0o/schemastore.nvim"

[[spec]]
plugin = "kosayoda/nvim-lightbulb"
config = "dharmx.configs.lsp.lightbulb"

[[spec]]
plugin = "SmiteshP/nvim-navic"
config = "dharmx.configs.lsp.navic"

[[spec]]
plugin = "simrat39/rust-tools.nvim"

[[spec]]
plugin = "mfussenegger/nvim-jdtls"

[[spec]]
plugin = "williamboman/mason-lspconfig.nvim"
dependencies = [ "williamboman/mason.nvim" ]
opts = "factory"

[[spec]]
plugin = "neovim/nvim-lspconfig"
cmd = "LspStart"
config = "dharmx.configs.lsp"

[[spec]]
plugin = "j-hui/fidget.nvim"
tag = "legacy"
event = "LspAttach"
config = "dharmx.configs.lsp.fidget"

[[spec]]
plugin = "mhartington/formatter.nvim"
event = "LspAttach"
config = "dharmx.configs.lsp.formatter"

[[spec]]
plugin = "jayp0521/mason-null-ls.nvim"
opts = "factory"

[[spec]]
plugin = "jose-elias-alvarez/null-ls.nvim"
dependencies = [ "WhoIsSethDaniel/mason-tool-installer.nvim", "jayp0521/mason-null-ls.nvim" ]
event = "LspAttach"
config = "dharmx.configs.lsp.null"

[[spec]]
plugin = "WhoIsSethDaniel/mason-tool-installer.nvim"
opts = "factory"

[[spec]]
plugin = "mfussenegger/nvim-dap"
dependencies = [ "jayp0521/mason-nvim-dap.nvim" ]

[[spec]]
plugin = "jayp0521/mason-nvim-dap.nvim"
config = "dharmx.configs.lsp.masondap"

[[spec]]
plugin = "rcarriga/nvim-dap-ui"
event = "LspAttach"
config = "dharmx.configs.lsp.dapui"

[[spec]]
plugin = "nvim-telescope/telescope.nvim"
dependencies = [ "nvim-telescope/telescope-symbols.nvim" ]
cmd = "Telescope"
config = "dharmx.configs.telescope"

[[spec]]
plugin = "dharmx/track.nvim"
dev = true
config = true
cmd = [ "Track", "TrackPick", "TrackMark", "TrackBundleAlternate", "TrackUnmark", "TrackStashBundle", "TrackRestoreBundle" ]

[[spec]]
plugin = "nvim-telescope/telescope-ui-select.nvim"

[[spec]]
plugin = "dharmx/telescope-media.nvim"
dev = true

[[spec]]
plugin = "nvim-telescope/telescope-symbols.nvim"

[[spec]]
plugin = "nvim-telescope/telescope-dap.nvim"

[[spec]]
plugin = "nvim-treesitter/nvim-treesitter"
event = "BufWinEnter"
build = ":TSUpdate"
config = "dharmx.configs.treesitter"

[[spec]]
plugin = "romgrk/nvim-treesitter-context"
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]
config = "dharmx.configs.treesitter.context"

[[spec]]
plugin = "andymass/vim-matchup"
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]
config = "dharmx.configs.treesitter.matchup"

[[spec]]
plugin = "mrjones2014/nvim-ts-rainbow"
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]
config = "dharmx.configs.treesitter.rainbow"

[[spec]]
plugin = "RRethy/nvim-treesitter-textsubjects"
keys = "factory"
config = "dharmx.configs.treesitter.textsubjects"

[[spec]]
plugin = "nvim-treesitter/nvim-treesitter-textobjects"
event = [ "CursorHold", "CursorMoved", "InsertEnter" ]
config = "dharmx.configs.treesitter.textobjects"

[[spec]]
plugin = "theHamsta/nvim-dap-virtual-text"
dependencies = [ "nvim-treesitter/nvim-treesitter" ]
event = "LspAttach"
config = "dharmx.configs.treesitter.dapvirtual"

[[spec]]
plugin = "nvim-tree/nvim-web-devicons"

[[spec]]
plugin = "petertriho/nvim-scrollbar"
event = [ "InsertEnter", "CursorMoved" ]
config = "dharmx.configs.ui.scrollbar"

[[spec]]
plugin = "rcarriga/nvim-notify"
event = [ "CursorMoved", "CursorHold", "InsertEnter", "CmdlineEnter" ]
config = "dharmx.configs.ui.notify"

[[spec]]
plugin = "folke/todo-comments.nvim"
event = [ "CursorMoved", "CursorHold", "InsertEnter", "CmdlineEnter" ]
config = "dharmx.configs.ui.todo"

[[spec]]
plugin = "doums/monark.nvim"
event = "InsertEnter"
opts = "factory"

[[spec]]
plugin = "lukas-reineke/indent-blankline.nvim"
event = [ "CursorMoved", "CursorHold", "InsertEnter" ]
config = "dharmx.configs.ui.indentline"

[[spec]]
plugin = "RRethy/vim-illuminate"
event = [ "InsertEnter", "CursorMoved" ]
config = "dharmx.configs.ui.illuminate"
